Convert help page to start page
BRL-CAD/arbalest pull request #48
Opened 2024-05-27 16:47 UTC by ViditJain123

I converted the landing page of the Arbalest to the start page by making the text clickable. Now one can create a New File or open an older one by just clicking the Text on the start page. I achieved this functionality by when Ctrl+N or Ctrl+O (text) is pressed in HelpWidget, it emits the signal, triggering newFile or openFile in MainWindow. This approach ensures communication between classes without tight coupling, enabling modular and maintainable code.

2024-05-28 06:04 UTC, Himanshu40 approved these changes

2024-06-05 21:36 UTC, Himanshu40 requested changes

2024-06-05 21:36 UTC, Himanshu40 commented on include/MainWindow.h
> +#include "HelpWidget.h"
Remove "HelpWidget.h".

2024-06-06 07:23 UTC, drossberg commented on src/gui/HelpWidget.cpp
> +HelpWidget::HelpWidget(QWidget* parent) : QVBoxWidget() {
Should QVBoxWidget() get *parent* as parameter? By the book, yes. The widget's parent will however be replaced when added to the document area.

2024-06-06 15:34 UTC, merged